[package]
name = "loco"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.7"
colored = "2.0"
